//Jobs
export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILED = 'FETCH_JOBS_FAILED';

//Single Job
export const FETCH_JOB_START = 'FETCH_JOB_START';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAILED = 'FETCH_JOB_FAILED';

//Authentication
export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_WITH_ERROR = 'AUTH_LOGOUT_WITH_ERROR';

//Candidates
export const FETCH_CANDIDATES_START = 'FETCH_CANDIDATES_START'
export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILED = 'FETCH_CANDIDATES_FAILED';

//SavedCandidates
export const FETCH_SAVED_CANDIDATES_START = 'FETCH_SAVED_CANDIDATES_START'
export const FETCH_SAVED_CANDIDATES_SUCCESS = 'FETCH_SAVED_CANDIDATES_SUCCESS';
export const FETCH_SAVED_CANDIDATES_FAILED = 'FETCH_SAVED_CANDIDATES_FAILED';

//Profile 
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED';
export const PROFILE_IS_NEW = 'PROFILE_IS_NEW';